defmodule Relay.Attachments.Storage do
  @moduledoc """
  Behaviour for attachment byte storage (RLY-13). Chosen by config so the
  suite and dev stay hermetic (`Local`) while prod uses object storage
  (`S3`). `key` is an opaque storage key generated by the context.
  """

  @callback put(key :: String.t(), bytes :: binary(), content_type :: String.t()) ::
              :ok | {:error, term()}
  @callback get(key :: String.t()) :: {:ok, binary()} | {:error, term()}
end
