defmodule Storybook.CoreComponents do
  @moduledoc false
  use PhoenixStorybook.Index

  def folder_open?, do: true

  def entry("avatar"), do: [icon: {:fa, "circle-user", :thin}]
  def entry("back"), do: [icon: {:fa, "circle-left", :thin}]
  def entry("blocked_strip"), do: [icon: {:fa, "hourglass-half", :thin}]
  def entry("board_card"), do: [icon: {:fa, "note-sticky", :thin}]
  def entry("board_view_tabs"), do: [icon: {:fa, "table-columns", :thin}]
  def entry("breadcrumbs"), do: [icon: {:fa, "angles-right", :thin}]
  def entry("button"), do: [icon: {:fa, "rectangle-ad", :thin}]
  def entry("card_mockups_section"), do: [icon: {:fa, "images", :thin}]
  def entry("card_review_panel"), do: [icon: {:fa, "clipboard-check", :thin}]
  def entry("card_search"), do: [icon: {:fa, "magnifying-glass", :thin}]
  def entry("compact_card_row"), do: [icon: {:fa, "list", :thin}]
  def entry("controls"), do: [icon: {:fa, "sliders", :thin}]
  def entry("copy_button"), do: [icon: {:fa, "clipboard", :thin}]
  def entry("dependency_list"), do: [icon: {:fa, "link", :thin}]
  def entry("error"), do: [icon: {:fa, "circle-exclamation", :thin}]
  def entry("flash"), do: [icon: {:fa, "bolt", :thin}]
  def entry("header"), do: [icon: {:fa, "heading", :thin}]
  def entry("icon"), do: [icon: {:fa, "icons", :thin}]
  def entry("image_attach_box"), do: [icon: {:fa, "paperclip", :thin}]
  def entry("image_attach_button"), do: [icon: {:fa, "paperclip", :thin}]
  def entry("image_attach_hint"), do: [icon: {:fa, "circle-info", :thin}]
  def entry("image_lightbox"), do: [icon: {:fa, "magnifying-glass-plus", :thin}]
  def entry("input"), do: [icon: {:fa, "input-text", :thin}]
  def entry("list"), do: [icon: {:fa, "list", :thin}]
  def entry("media_placeholder"), do: [icon: {:fa, "image-slash", :thin}]
  def entry("member_stack"), do: [icon: {:fa, "people-group", :thin}]
  def entry("meta_label"), do: [icon: {:fa, "tag", :thin}]
  def entry("mobile_nav_bar"), do: [icon: {:fa, "chevron-left", :thin}]
  def entry("mockup_preview"), do: [icon: {:fa, "window-maximize", :thin}]
  def entry("mockup_viewer_bar"), do: [icon: {:fa, "mobile-screen", :thin}]
  def entry("mockup_viewer_pager"), do: [icon: {:fa, "ellipsis", :thin}]
  def entry("mockup_viewer_zoom"), do: [icon: {:fa, "magnifying-glass-plus", :thin}]
  def entry("modal_scrim"), do: [icon: {:fa, "layer-group", :thin}]
  def entry("note_image_row"), do: [icon: {:fa, "image", :thin}]
  def entry("notification_settings"), do: [icon: {:fa, "bell", :thin}]
  def entry("notification_toast"), do: [icon: {:fa, "message-exclamation", :thin}]
  def entry("owner_avatars"), do: [icon: {:fa, "user-group", :thin}]
  def entry("owner_pill"), do: [icon: {:fa, "tag", :thin}]
  def entry("page_heading"), do: [icon: {:fa, "heading", :thin}]
  def entry("plan_tasks"), do: [icon: {:fa, "list-check", :thin}]
  def entry("section_label"), do: [icon: {:fa, "heading", :thin}]
  def entry("segmented_control"), do: [icon: {:fa, "toggle-on", :thin}]
  def entry("stage_column"), do: [icon: {:fa, "table-columns", :thin}]
  def entry("table"), do: [icon: {:fa, "table", :thin}]
end
