defmodule Relay.Attachments.Storage.Local do
  @moduledoc """
  Filesystem storage adapter for attachments (RLY-13) — dev/test. Writes
  bytes under a gitignored local dir (default `priv/uploads/attachments/`)
  keyed by the storage key, so tests are hermetic and need no network.
  """

  @behaviour Relay.Attachments.Storage

  # `key` is an opaque storage key generated by the context (an
  # `Ecto.UUID.generate/0` string), never taken verbatim from user input.
  # `path_for/1` also strips any path separators via `Path.basename/1`, so a
  # key can never escape `dir()`.
  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def put(key, bytes, _content_type) do
    path = path_for(key)
    File.mkdir_p!(Path.dirname(path))
    File.write(path, bytes)
  end

  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def get(key) do
    case File.read(path_for(key)) do
      {:ok, bytes} -> {:ok, bytes}
      {:error, reason} -> {:error, reason}
    end
  end

  defp path_for(key), do: Path.join(dir(), Path.basename(key))

  defp dir do
    :relay
    |> Application.get_env(__MODULE__, [])
    |> Keyword.get(:dir, Path.join(["priv", "uploads", "attachments"]))
  end
end
